<?php

namespace AppBundle\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAnwsersByPost($post)
    {
        $qb = $this->createQueryBuilder('a');
        $qb->select('a.author,a.text,a.createdAt')
            ->orderBy("a.createdAt", "desc")
            ->innerJoin('a.post','p')
            ->where('a.post=:post')
            ->setParameter('post', $post);
        //$qb->getDQL();
        return $qb;
    }
}
